<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-CJB084VV" failures="1" tests="31" name="runner.TestRunner" time="150.210" errors="0" timestamp="2023-11-24T16:26:22 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="2.612"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.339"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.194"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.211"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.060"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.404"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.486"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.188"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.114"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.942"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="17.765"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.313"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.968"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.360"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.227"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="8.664"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.915">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepDefinition.RegistrationSD.user_should_be_redirected_to_the_home_page_with_the_message_username(RegistrationSD.java:123)
at âœ½.User should be redirected to the home page with the message "New Account Created. You are logged in as "<Username>""(file:///C:/Users/satya/eclipse-workspace/DSAlgoTest/src/test/resources/features/02Register.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="1.823"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.998"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.725"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.306"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.122"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.130"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.182"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.252"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.705"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.118"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.290"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.829"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.432"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.536"/>
</testsuite> <!-- runner.TestRunner -->
